// Programar el acceso a mi boda

var Invitados = (
    "Papá Suegro Genaro",
    "Mamá Suegra Yovis",
    "GENARITO",
    "ABUELITA ALICIA",
    "IRVING",
    "YURI",
    "ABUELITA",
    "TONY",
    "TIA NORMA",
    "TIO SERGIO",
    "JENNY",
    "LUCY",
    "ABUELITO LUIS",
    "AMALIA",
    "NENA",
    "BETO",
    "EDWIN",
    "MUJER DEL EDWIN",
    "DIEGO",
    "VERO",
    "JUAN CARLOS",
    "PERLA",
    "ALE",
    "MICHELL",
    "ARTURO",
    "EMA",
    "NOVIO DE EMA",
    "ADOLFO",
    "NOVIO DE CARLOS",
    "MARIFER",
    "DANI",
    "NOVIA DEL DANI",
    "TIA CHELO",
    "LIZ",
    "MAYRA",
    "MIGUEL",
    "ALONDRA",
    "IVAN",
    "LETI",
    "SAMI",
    "TITA",
    "ANDY",
    "YOYO",
    "ALETS",
    "NOVIA DEL ALETS",
    "REBECA",
    "NOVIO DE REBECA",
    "YHAIR",
    "POC",
    "SEÑORA DE POC",
    "BRYAN",
    "LA NOVIA DEL BRYAN",
    "BUENO",
    "EVER",
    "MAMÁ",
    "PAPÁ",
    "CARLO",
    "SEÑORA DE CARLO",
    "TIA CARMEN",
    "PEPE",
    "LUCERO",
    "DANIELA",
    "DANIEL",
    "YARE",
    "TIO CARLOS",
    "TIO ARNULFO",
    "TIO JUAN",
    "LILIANA",
    "SAMI DE TIO JUAN",
    "SARITA",
    "LA SEÑORA SARITA",
    "EL PIPAS",
    "ESPOSA DEL PIPAS",
    "EMILY",
    "JOSE LUIS",
    "ESPOSA DE JOSE LUIS",
    "HIJA DE JOSE LUIS");

var Nombres = [
    {Nombre: "YARE"},
    {Nombre: "TIO CARLOS"},
    {Nombre: "TIO ARNULFO"},
    {Nombre: "TIO JUAN"},
    {Nombre: "LILIANA"},
    {Nombre: "SAMI DE TIO JUAN"},
    {Nombre: "SARITA"},
    {Nombre: "LA SEÑORA SARITA"},
    {Nombre: "EL PIPAS"},
    {Nombre: "ESPOSA DEL PIPAS"},
    {Nombre: "EMILY"},
    {Nombre: "JOSE LUIS"},
    {Nombre: "ESPOSA DE JOSE LUIS"},
    {Nombre: "HIJA DE JOSE LUIS"},  
];
if (Invitados == Nombres()) {
    console.log("Invitado");}
    else { 
        console.log("No Invitado");

}

